apiVersion: v1
kind: Service
metadata:
  name: elements-recorder-api-ip
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 31112
  selector:
    app: elements-recorder-api
