apiVersion: v1
kind: Service
metadata:
  name: elements-recorder-db-ip
spec:
  ports:
    - port: 5432
  selector:
    app: elements-recorder-db
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elements-recorder-db
spec:
  selector:
    matchLabels:
      app: elements-recorder-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: elements-recorder-db
    spec:
      containers:
        - image: postgres:13.3
          name: elements-recorder-db
          env:
            # Use secret in real usage
            - name: POSTGRES_USER
              value: elements_recorder_app
            - name: POSTGRES_PASSWORD
              value: root
          ports:
            - containerPort: 5432
              name: postgresql
          volumeMounts:
            - name: postgresql-persistent-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgresql-persistent-storage
          persistentVolumeClaim:
            claimName: postgresql-pv-claim
