version: '3.7'

services:

  api:
    build: back/
    ports:
      - 8080:8080
    networks:
      - website
    container_name: api

  front:
    build: front/
    ports:
      - 4200:80
    hostname: front
    networks:
      - website
    container_name: front
    depends_on:
      - api

networks:
  website:
    driver: bridge
    name: website
