spring:
  datasource:
    url: jdbc:postgresql://82.124.30.70:5432/elements_recorder
    username: prod_elements_recorder_app
    password: ${SPRING_DATASOURCE_PASSWORD}
    hikari:
      initializationFailTimeout: 5000
