spring:
  datasource:
    url: jdbc:postgresql://${SPRING_DATASOURCE_IP}:${SPRING_DATASOURCE_PORT}/${SPRING_DATASOURCE_DB_NAME}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    hikari:
      initializationFailTimeout: 5000
  jackson:
    property-naming-strategy: SNAKE_CASE

app:
  jwt:
    secret: ${JWT_SECRET}
    validity: 1440