spring:
  datasource:
    url: jdbc:postgresql://192.168.1.28:5432/elements_recorder
    username: elements_recorder_app
    password: root

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE