spring:
  datasource:
    url: jdbc:mysql://localhost:3306/elements_recorder?serverTimezone=UTC
    username: root
    password: root

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE